### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [rloyaa/prj-rev-bwfs-dasmoto#6]
https://github.com/rloyaa/prj-rev-bwfs-dasmoto/blob/master/art/resources/Style.css#L2-L18

There's a bit of repetition here.

Move shared styles into a single CSS rule with a more general selector, so that you don't have to repeat the style in every single CSS rule.

```css
* {
  font-family: Helvetica;
}
```
